### ISSUE TITLE
django failure "django_settings_module='Could not import the specified DJANGO_SETTINGS_MODULE: bakerydemo.settings'"

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

django seems to be failing on bakerydemo. It should work.

### Actual Behavior

```
sys.path=['/var/www/html', '/usr/local/bin', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/var/www/html/.ddev/.venv/lib/python3.9/site-packages']
WSGI_APP environment variable=None DJANGO_SETTINGS_MODULE=bakerydemo.settings.local
settings_file='Could not import the specified DJANGO_SETTINGS_MODULE: bakerydemo.settings.local
None
'
django_settings_module='Could not import the specified DJANGO_SETTINGS_MODULE: bakerydemo.settings'
Traceback (most recent call last):
  File "/usr/local/bin/start-gunicorn.py", line 65, in <module>
    wsgi_application = settings.WSGI_APPLICATION
  File "/var/www/html/.ddev/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/var/www/html/.ddev/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/www/html/.ddev/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Could not import the specified DJANGO_SETTINGS_MODULE: bakerydemo'
failed to start gunicorn
```

Somehow DJANGO_SETTINGS_MODULE got set wrong, 
`django_settings_module='Could not import the specified DJANGO_SETTINGS_MODULE: bakerydemo.settings'`

**Comment by rfay** [comment]
Closing for now.
