### ISSUE TITLE
DDEV Integration PhpStorm plugin freezes on installation

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#4996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output in console after 1. Starting PhpStorm and 2. Installing the plugin

<details><summary>1. Expand PhpStorm start up feedback</summary>

```
$ ~/.local/bin/PhpStorm-231.9011.38/bin/phpstorm.sh
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
2023-06-17 11:27:30,452 [   1121]   WARN - #c.i.o.v.n.p.l.VfsLog - VFS Log version differs from the implementation version: log null vs implementation -43
2023-06-17 11:27:30,904 [   1573]   WARN - #c.j.p.PluginClassPathRuntimeCustomizer - There was more than one class loaded in Projector Plugin classloader - this is likely a bug!
Info  | RdCoroutineScope          | 61:DefaultDispatcher-worker-43 | RdCoroutineHost overridden 
2023-06-17 11:27:33,601 [   4270]   WARN - #c.i.o.w.i.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Robo tasks) or icon RasterizedImageDataLoader(classLoader=PluginClassLoader(plugin=PluginDescriptor(name=PHP, id=com.jetbrains.php, descriptorPath=plugin.xml, path=~/.local/bin/PhpStorm-231.9011.38/plugins/php-impl, version=231.9011.38, package=null, isBundled=true), packagePrefix=null, instanceId=104, state=active), path=icons/php-icon.svg)
2023-06-17 11:27:34,474 [   5143]   WARN - #c.i.i.s.p.i.BundledSharedIndexPostStartupActivity - Skipped 1 pre-built shared indexes: bundled-js-predefined-1d06a55b98c1-e95fd0b84d23-JavaScript-PS-231.9011.38
2023-06-17 11:27:37,988 [   8657]   WARN - #c.j.p.PhpIndex - Completing type '#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle' took 1171ms, visited:[#π(#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle)((#π(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals))(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals)), #M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle]
```
</details>

<details><summary>2. Expand PhpStorm Error message after installing the plugin</summary>

```
2023-06-17 11:27:37,988 [   8657]   WARN - #c.j.p.PhpIndex - Completing type '#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle' took 1163ms, visited:[#π(#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle)((#π(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals))(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals)), #M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle]
2023-06-17 11:27:37,988 [   8657]   WARN - #c.j.p.PhpIndex - Completing type '#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals' took 1156ms, visited:[#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals]
2023-06-17 11:27:37,988 [   8657]   WARN - #c.j.p.PhpIndex - Completing type '#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals' took 1176ms, visited:[#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals]
2023-06-17 11:27:37,988 [   8657]   WARN - #c.j.p.PhpIndex - Completing type '#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle' took 1176ms, visited:[#π(#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle)((#π(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals))(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals)), #M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle]
2023-06-17 11:27:37,987 [   8656]   WARN - #c.j.p.PhpIndex - Completing type '#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle' took 591ms, visited:[#π(#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle)((#π(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals))(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals)), #M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle]
2023-06-17 11:27:37,987 [   8656]   WARN - #c.j.p.PhpIndex - Completing type '#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle' took 526ms, visited:[#π(#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle)((#π(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals))(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals)), #M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle]
2023-06-17 11:27:37,987 [   8656]   WARN - #c.j.p.PhpIndex - Completing type '#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle' took 1131ms, visited:[#π(#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle)((#π(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals))(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals)), #M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle]
2023-06-17 11:27:37,987 [   8656]   WARN - #c.j.p.PhpIndex - Completing type '#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle' took 1131ms, visited:[#π(#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle)((#π(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals))(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals)), #M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle]
2023-06-17 11:27:37,987 [   8656]   WARN - #c.j.p.PhpIndex - Completing type '#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle' took 1281ms, visited:[#π(#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle)((#π(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals))(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals)), #M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle]
2023-06-17 11:27:37,988 [   8657]   WARN - #c.j.p.PhpIndex - Completing type '#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle' took 1174ms, visited:[#π(#M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle)((#π(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals))(#M#C\Symfony\Component\HttpFoundation\Request.createFromGlobals)), #M#耒(\Drupal\Core\DrupalKernel)((\string))((\mixed)).handle]
^A2023-06-17 11:28:30,222 [  60891]   WARN - #c.i.o.o.e.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager
2023-06-17 11:28:30,252 [  60921]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme WarmNeon - old: WarmNeon, new WarmNeon
2023-06-17 11:28:30,253 [  60922]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Twilight - old: Twilight, new Twilight
2023-06-17 11:28:30,255 [  60924]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme VibrantInk - old: VibrantInk, new VibrantInk
2023-06-17 11:28:30,264 [  60933]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Monokai - old: Monokai, new Monokai
2023-06-17 11:28:30,265 [  60934]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Railscasts - old: Railscasts, new Railscasts
2023-06-17 11:28:30,267 [  60936]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Solarized Light - old: Solarized Light, new Solarized Light
2023-06-17 11:28:30,270 [  60939]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Solarized Dark - old: Solarized Dark, new Solarized Dark
2023-06-17 11:28:30,272 [  60941]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Cobalt - old: Cobalt, new Cobalt
2023-06-17 11:28:30,273 [  60942]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme All hallow's eve - old: All hallow's eve, new All hallow's eve
2023-06-17 11:28:30,275 [  60944]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Blackboard - old: Blackboard, new Blackboard
2023-06-17 11:28:30,275 [  60944]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme IntelliJ Light - old: IntelliJ Light, new IntelliJ Light
2023-06-17 11:28:30,276 [  60945]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme High contrast - old: High contrast, new High contrast
2023-06-17 11:28:30,277 [  60946]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Darcula Contrast - old: Darcula Contrast, new Darcula Contrast
2023-06-17 11:28:30,278 [  60947]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Dark - old: Dark, new Dark
2023-06-17 11:28:30,278 [  60947]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Light - old: Light, new Light
2023-06-17 11:28:30,300 [  60969]   WARN - #c.i.o.o.e.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager
2023-06-17 11:28:30,302 [  60971] SEVERE - #c.i.o.u.ObjectTree - Window must not be zero
java.lang.IllegalArgumentException: Window must not be zero
  at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:56)
  at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:73)
  at java.desktop/sun.awt.X11.XlibUtil.isToplevelWindow(XlibUtil.java:253)
  at java.desktop/sun.awt.X11.XWindowPeer.setToplevelTransientFor(XWindowPeer.java:1799)
  at java.desktop/sun.awt.X11.XWindowPeer.restoreTransientFor(XWindowPeer.java:2013)
  at java.desktop/sun.awt.X11.XWindowPeer.removeFromTransientFors(XWindowPeer.java:2077)
  at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1752)
  at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1723)
  at java.desktop/java.awt.Window.setModalBlocked(Window.java:1559)
  at java.desktop/java.awt.Dialog.unblockWindow(Dialog.java:1569)
  at java.desktop/java.awt.Dialog.modalHide(Dialog.java:1455)
  at java.desktop/java.awt.Dialog.hideAndDisposePreHandler(Dialog.java:1130)
  at java.desktop/java.awt.Dialog.hide(Dialog.java:1159)
  at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.hide(DialogWrapperPeerImpl.java:789)
  at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.dispose(DialogWrapperPeerImpl.java:795)
  at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
  at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
  at com.intellij.openapi.util.Disposer.dispose(Disposer.java:264)
  at com.intellij.openapi.util.Disposer.dispose(Disposer.java:252)
  at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.lambda$dispose$1(DialogWrapperPeerImpl.java:250)
  at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
  at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.dispose(DialogWrapperPeerImpl.java:260)
  at com.intellij.openapi.ui.DialogWrapper.dispose(DialogWrapper.java:928)
  at com.intellij.openapi.ui.DialogWrapper$1.dispose(DialogWrapper.java:153)
  at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
  at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
  at com.intellij.openapi.util.Disposer.dispose(Disposer.java:264)
  at com.intellij.openapi.util.Disposer.dispose(Disposer.java:252)
  at com.intellij.openapi.ui.DialogWrapper.close(DialogWrapper.java:461)
  at com.intellij.openapi.ui.DialogWrapper.close(DialogWrapper.java:465)
  at com.intellij.openapi.ui.DialogWrapper.doOKAction(DialogWrapper.java:1032)
  at com.intellij.openapi.options.newEditor.SettingsDialog.applyAndClose(SettingsDialog.java:205)
  at com.intellij.openapi.options.newEditor.SettingsDialog.doOKAction(SettingsDialog.java:193)
  at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1863)
  at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1817)
  at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
  at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
  at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
  at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
  at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
  at java.desktop/java.awt.Component.processMouseEvent(Component.java:6656)
  at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
  at java.desktop/java.awt.Component.processEvent(Component.java:6421)
  at java.desktop/java.awt.Container.processEvent(Container.java:2266)
  at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
  at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
  at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
  at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
  at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
  at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
  at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
  at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
  at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
  at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
  at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
  at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
  at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
  at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
  at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:615)
  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
  at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
  at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
  at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
  at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
  at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
  at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
  at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
  at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
  at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
  at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
  at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
  at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
  at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
  at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
  at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
  at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
  at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:741)
  at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:466)
  at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1675)
  at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1633)
  at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)
  at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:60)
  at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:47)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
  at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:585)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:707)
  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
  at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:707)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:704)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:596)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:480)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:469)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
  at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:599)
  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
  at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
  at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
  at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
  at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
  at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
  at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
  at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
  at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
  at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
  at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
  at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
  at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-06-17 11:28:30,307 [  60976] SEVERE - #c.i.o.u.ObjectTree - PhpStorm 2023.1.2  Build #PS-231.9011.38
2023-06-17 11:28:30,307 [  60976] SEVERE - #c.i.o.u.ObjectTree - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-06-17 11:28:30,307 [  60976] SEVERE - #c.i.o.u.ObjectTree - OS: Linux
2023-06-17 11:28:30,315 [  60984]   WARN - #c.i.o.w.i.s.w.StatusBarWidgetsManager - Factory is not registered as `com.intellij.statusBarWidgetFactory` extension: de.php_perfect.intellij.ddev.statusBar.DdevStatusBarWidgetImpl
```
</details>

### Expected Behavior

That the [DDEV integration](https://plugins.jetbrains.com/plugin/18813-ddev-integration) plugin for PhpStorm would install without errors, so that the automatic plug and play installation of [PhpStorm and Xdebug in DDEV](https://www.drupal.org/docs/develop/development-tools/editors-and-ides/configuring-phpstorm#s-ddev-setup) works again.

Ideally, it should be as easy to set up as it used to be:

#### DDEV setup
<p>Setting up Xdebug in DDEV is extremely easy. Open PhpStorm and then:</p>
<ol>
<li>Install the <a href="http://plugins.jetbrains.com/plugin/18813-ddev-integration" rel="nofollow">DDEV Integration Plugin</a> via <em>Preferences → Plugins → Marketplace</em></li>
<li>Enable "Use Compose V2" under <em>Build, Execution, Deployment → Docker → Tools</em></li>
<li>Restart DDEV and start Xdebug by running <code class=" language-php">ddev xdebug</code></li>
</ol>

From https://www.drupal.org/docs/develop/development-tools/editors-and-ides/configuring-phpstorm#s-ddev-setup

### Actual Behavior

I get an error, and PhpStorm freezes. Also, the easy three step set up of Xdebug in PhpStorm with DDEV doesn't work. 

## Versions

Ubuntu 20.04.6 LTS

PhpStorm 2023.1.2
Build #PS-231.9011.38, built on May 16, 2023

```
$ ddev version
 ITEM             VALUE                                   
 DDEV version     v1.21.6                                 
 architecture     amd64                                   
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.5 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.5             
 docker           24.0.2                                  
 docker-compose   v2.15.1                                 
 docker-platform  local                                    
 mutagen          0.16.0                                  
 os               linux                                   
 router           drud/ddev-router:v1.21.5                
 web              drud/ddev-webserver:v1.21.5   
```
DDEV Integration
Version 1.1.0, May 19, 2023
https://plugins.jetbrains.com/plugin/18813-ddev-integration

## Reproduce

Install the latest DDEV Integration plugin in the latest PhpStorm, and see that it freezes. Also, the PhpStorm/Xdebug/DDEV easy set up, doesn't work.

**Comment by rfay** [comment]
Hi @gitressa - This isn't the place to report this, and I'm afraid the information you have isn't going to make it easy to solve. Lots of people are using it, and they're not yet reporting any of this. 

Places you can report this are the Plugin issue queue: https://github.com/php-perfect/ddev-intellij-plugin/issues

Or the Jetbrains issue queue, https://youtrack.jetbrains.com/issues

But I imagine you'll have to figure out how to get more specific information before anything will be actionable. 

Closing here.

**Comment by gitressa** [comment]
Thanks for the pointers @rfay, I have created https://github.com/php-perfect/ddev-intellij-plugin/issues/194.
