### ISSUE TITLE
Panic when `upload-dirs` is false

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#5126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

```
$ ddev version
 ITEM             VALUE                                               
 DDEV version     v1.22.0-beta3-10-g42969991                          
 architecture     amd64                                               
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.0-beta1       
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.0-beta1                   
 docker           24.0.2                                              
 docker-compose   v2.20.0                                             
 docker-platform  dev                                                 
 mutagen          0.17.2                                              
 os               linux                                               
 router           traefik:v2.10                                       
 web              ddev/ddev-webserver:20230707_fix_process_group_kill
```

### Expected Behavior

From  `.ddev/config.yaml`, `upload_dirs` can be `false`:

```
# upload_dirs: "custom/upload/dir"
#
# upload_dirs:
#   - custom/upload/dir
#   - ../private
#
# upload_dirs: false
```

https://github.com/ddev/ddev/blob/42969991212ff2c71fb91d7651d2ea17f8d1d749/pkg/ddevapp/upload_dirs.go#L211-L212

### Actual Behavior

```
$ ddev config --auto --upload-dirs=false
Creating a new ddev project config in the current directory (/home/user/test) 
Once completed, your configuration will be written to /home/user/test/.ddev/config.yaml
 
Configuring unrecognized codebase as project of type 'php' at /home/user/test 
Configuration complete. You may now run 'ddev start'. 
panic: interface conversion: interface {} is bool, not ddevapp.UploadDirs

goroutine 1 [running]:
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).validateUploadDirs(0xc000103c00)
        /home/runner/work/ddev/ddev/pkg/ddevapp/upload_dirs.go:230 +0x485
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).LoadConfigYamlFile(0xc000103c00, {0xc000418db0?, 0xc00017b040?})
        /home/runner/work/ddev/ddev/pkg/ddevapp/config.go:363 +0x1b2
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).ReadConfig(0xc000103c00, 0x0)
        /home/runner/work/ddev/ddev/pkg/ddevapp/config.go:317 +0x4b
github.com/ddev/ddev/pkg/ddevapp.NewApp({0x0, 0x0}, 0x8?)
        /home/runner/work/ddev/ddev/pkg/ddevapp/config.go:112 +0x825
github.com/ddev/ddev/cmd/ddev/cmd.glob..func48(0x10f7500, {0xc000312340?, 0x0?, 0x2?})
        /home/runner/work/ddev/ddev/cmd/ddev/cmd/root.go:101 +0x57
github.com/spf13/cobra.(*Command).execute(0x10f7500, {0xc000312320, 0x2, 0x2})
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:876 +0x770
github.com/spf13/cobra.(*Command).ExecuteC(0x10f5480)
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:902
github.com/ddev/ddev/cmd/ddev/cmd.Execute()
        /home/runner/work/ddev/ddev/cmd/ddev/cmd/root.go:163 +0x25
main.main()
        /home/runner/work/ddev/ddev/cmd/ddev/main.go:28 +0xc5
```

### Steps To Reproduce

1. `ddev config --auto --upload-dirs=false`

**Comment by rfay** [comment]
Thanks so much, didn't do this last time I tested!

**Comment by rfay** [comment]
I'm able to reproduce this.

**Comment by rfay** [comment]
Thanks, @stasadev - I think 
* https://github.com/ddev/ddev/pull/5128#issuecomment-1633107095 will fix both of the issues you had (panic and laravel with import-files). 

I'd sure appreciate if you could test and review, thanks!
